version: '2'
services:
  deployer:
    image: "crafter-deployer:2.5.2"
    volumes:
      - ./conf/deployer-conf:/opt/crafter-deployer/conf
      - ./data/deployer-target:/opt/crafter-deployer/target
    links:
      - search-studio
      - search-delivery
  delivery:
    image: "crafter-engine:2.5.2"
    ports:
      - "9090:8080"
    volumes:
      - ./conf/delivery-shared:/usr/local/tomcat/shared
      - ./data/deployer-target:/opt/crafter-deployer/target
    links:
      - search-delivery
  search-delivery:
    image: "crafter-search:2.5.2"
    volumes:
      - ./data/search-delivery-data:/usr/local/tomcat/solr-crafter/data
    ports:
      - "9091:8080"
  search-studio:
    image: "crafter-search:2.5.2"
    volumes:
      - ./data/search-studio-data:/usr/local/tomcat/solr-crafter/data
    ports:
      - "8081:8080"
  studio:
    image: "crafter-studio:2.5.2"
    ports:
      - "8080:8080"
      - "8009:8009"
    volumes:
      - ./conf/studio-shared:/usr/local/tomcat/shared
      - ./data/studio-db:/usr/local/tomcat/data/derby
      - ./data/studio-repo:/usr/local/tomcat/data/repo
      - ./data/deployer-target:/opt/crafter-deployer/target
    links:
      - search-studio
      - deployer
